// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHC_r5zx0AIaTLPtAqGDv-VhUqflK_IhQ',
    appId: '1:1008750748709:web:5f7e69a4d15507baf98bcc',
    messagingSenderId: '1008750748709',
    projectId: 'chat-with-7f5cd',
    authDomain: 'chat-with-7f5cd.firebaseapp.com',
    storageBucket: 'chat-with-7f5cd.firebasestorage.app',
    measurementId: 'G-TVBGMCCEHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKxndUwHbMeTuGBbOM4IIXxye28pAyQvw',
    appId: '1:1008750748709:android:1fae7e6e2143f512f98bcc',
    messagingSenderId: '1008750748709',
    projectId: 'chat-with-7f5cd',
    storageBucket: 'chat-with-7f5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_7YBDPojXchZeaIBwE0FojgAcQbRX_Xk',
    appId: '1:1008750748709:ios:384cf4c29d20c0cbf98bcc',
    messagingSenderId: '1008750748709',
    projectId: 'chat-with-7f5cd',
    storageBucket: 'chat-with-7f5cd.firebasestorage.app',
    iosBundleId: 'com.example.chatWith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_7YBDPojXchZeaIBwE0FojgAcQbRX_Xk',
    appId: '1:1008750748709:ios:384cf4c29d20c0cbf98bcc',
    messagingSenderId: '1008750748709',
    projectId: 'chat-with-7f5cd',
    storageBucket: 'chat-with-7f5cd.firebasestorage.app',
    iosBundleId: 'com.example.chatWith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHC_r5zx0AIaTLPtAqGDv-VhUqflK_IhQ',
    appId: '1:1008750748709:web:eff5dfbb52dc3ea4f98bcc',
    messagingSenderId: '1008750748709',
    projectId: 'chat-with-7f5cd',
    authDomain: 'chat-with-7f5cd.firebaseapp.com',
    storageBucket: 'chat-with-7f5cd.firebasestorage.app',
    measurementId: 'G-H7YLVNZ4KV',
  );
}
